In [1]:
import pandas as pd
from pathlib import Path
import zipfile

In [2]:
text = '/home/daria/Downloads/REALEC_texts.zip'
preds = '/home/daria/Downloads/REALEC_predictions.csv'

In [3]:
with zipfile.ZipFile(text) as file:
  file.extractall('files')

In [4]:
ls

CompLing/                     Pictures/
Databases_Bachelors_2020-21/  Public/
Desktop/                      REALEC_extract.ipynb
Documents/                    rstudio-server-2021.09.2-382-amd64.deb
Downloads/                    Scientific_Programming_2022/
files/                        snap/
MachineLearning/              Templates/
Music/                        Videos/
nltk_data/

In [5]:
files = list(Path('files').iterdir())

In [6]:
def read_text(path):
    with open(path) as file:
        txt = file.readlines()
    return txt, path.name

In [7]:
txt = {name: ' '.join(txt) for txt, name in map(read_text, files)}

In [8]:
levels = pd.read_csv(preds, index_col=0)

In [9]:
levels

,der_level3,der_level4,der_level5,der_level6,mci,num_gerunds,density,ls,vs,corrected_vs,...,num_pres_sing,num_pres_plur,num_past_part,num_past_simple,num_misspelled_tokens,punct_mistakes_pp,punct_mistakes_because,punct_mistakes_but,punct_mistakes_compare,CEFR
name,,,,,,,,,,,,,,,,,,,,,
AAl_1_1.txt,0.022727,0.045455,0.022727,0.181818,4.75,2,0.466368,0.269231,0.000000,0.000000,...,9,0,8,2,3,0,0,1,0,B1-B2
AAl_1_2.txt,0.044444,0.122222,0.100000,0.044444,3.00,1,0.495549,0.125749,0.062500,0.250000,...,9,0,8,1,2,0,0,4,0,B1
AAl_11_2.txt,0.030303,0.040404,0.070707,0.121212,4.00,5,0.477654,0.111111,0.105263,0.458831,...,12,0,4,9,1,0,0,2,1,B1
AAl_12_1.txt,0.045455,0.075758,0.015152,0.045455,6.50,3,0.422713,0.313433,0.214286,0.801784,...,8,0,13,4,3,0,0,0,0,B1
AAl_12_2.txt,0.068966,0.172414,0.126437,0.068966,4.50,2,0.480226,0.088235,0.125000,0.500000,...,12,0,5,4,3,1,1,1,0,B1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VPe_35_1.txt,0.048780,0.024390,0.000000,0.073171,3.75,3,0.379167,0.296703,0.058824,0.171499,...,1,0,5,9,1,0,0,0,0,B1
VPe_35_2.txt,0.021739,0.173913,0.032609,0.032609,1.75,1,0.498708,0.134715,0.000000,0.000000,...,2,0,1,6,3,0,0,0,0,B1
VPe_36_1.txt,0.000000,0.083333,0.041667,0.020833,6.00,2,0.390374,0.219178,0.062500,0.176777,...,8,0,8,2,3,0,1,3,0,A2-B1
AAl_14_2.txt,0.034091,0.056818,0.045455,0.068182,3.75,1,0.442815,0.099338,0.161290,0.635001,...,12,0,6,5,3,0,0,0,0,B1-B2
KKo_24_1.txt,0.000000,0.079365,0.063492,0.015873,4.25,3,0.495614,0.026549,0.055556,0.166667,...,1,0,4,2,2,2,0,1,0,B2

In [24]:
levels.assign(text=pd.DataFrame(txt.values(), index=txt.keys()))[['CEFR', 'text']].query('CEFR=="B2"').text.iloc[8]

'The issue about whether to accept equal numbers of boys and girls to the Universities in controversial one and open for debate. In my opinion, in our modern world society all student should have equal rights in everything, no matter what gender he or she is. In this essay I will list some reasons to support my point of view. \n On the one hand, some people think that there is no need to make equal number of male and female students for a certain classes because they have different abilities to learn the subject. In particular, it is assumed that one very good at math, physics and so on, and give are very likely to be a good at literature, art and etc. \n On another hand, there is also a known fact that nowadays there are many professional sienticts in different fields and it is also does not depend on on the gender, in another words, gires as well as boys show excellent results in any subject, so there is no correlation with subject and gender. \n Personally, I believe that in one circle cociety we should not neglect this problem. Moreover, I tell that the equal number of male and female students will impact on the development of science positively. \n To summarize, there are different views about how students should be accepted to Universities. From my point of view, male and female student have equal abilities that is why there should have equal rights to study in universities.'